# Generated by Django 4.0.6 on 2022-07-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=500)),
                ('dob', models.DateField()),
                ('qualification', models.CharField(max_length=200)),
                ('enquiry_for', models.CharField(max_length=200)),
                ('other_course', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('whatsapp', models.BigIntegerField()),
                ('emplyment_status', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=200)),
                ('next_enquiry', models.DateField()),
                ('last_enquiry', models.DateTimeField()),
                ('enquiry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
