# Generated by Django 4.0.6 on 2022-07-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='last_enquiry',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='next_enquiry',
            field=models.DateField(blank=True),
        ),
    ]
