# Generated by Django 4.0.6 on 2022-07-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0003_alter_enquiry_last_enquiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='specialisation',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
