# Generated by Django 4.0.6 on 2022-07-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_enquiry_specialisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='last_enquiry',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='next_enquiry',
            field=models.DateField(default=None),
        ),
    ]
