# Generated by Django 4.0.5 on 2022-07-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0005_alter_enquiry_last_enquiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='last_enquiry',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='next_enquiry',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='reference',
            field=models.CharField(default='Self', max_length=200),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='specialisation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='whatsapp',
            field=models.BigIntegerField(null=True),
        ),
    ]
