# Generated by Django 4.0.5 on 2022-07-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0006_alter_enquiry_last_enquiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_for',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='reference',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
