# Generated by Django 4.0.5 on 2022-08-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0008_alter_enquiry_other_course_alter_enquiry_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='admission_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='last_enquiry_info',
            field=models.CharField(default='Not answered', max_length=200),
        ),
    ]
